# Generated by Django 6.0.1 on 2026-05-07 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_create_missing_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('Member', 'Member'), ('Market Seller', 'Market Seller'), ('Event Organizer', 'Event Organizer'), ('Book Contributor', 'Book Contributor'), ('Commission Maker', 'Commission Maker'), ('Project Creator', 'Project Creator')], default='Member', max_length=31),
        ),
    ]
