# Generated by Django 6.0.1 on 2026-03-03 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookclub', '0003_alter_book_options_alter_genre_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-publication_year'], 'verbose_name': 'book', 'verbose_name_plural': 'books'},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='createdOn',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='pubYear',
            new_name='publication_year',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='updatedOn',
            new_name='updated_on',
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='bookclub.genre'),
        ),
    ]
